[2022-10-13T21:33:15.421+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: trabalho2.also_run_this manual__2022-10-13T21:33:13.093239+00:00 [queued]>
[2022-10-13T21:33:15.434+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: trabalho2.also_run_this manual__2022-10-13T21:33:13.093239+00:00 [queued]>
[2022-10-13T21:33:15.434+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-13T21:33:15.434+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-13T21:33:15.434+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-13T21:33:15.451+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): also_run_this> on 2022-10-13 21:33:13.093239+00:00
[2022-10-13T21:33:15.458+0000] {standard_task_runner.py:54} INFO - Started process 284 to run task
[2022-10-13T21:33:15.461+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'trabalho2', 'also_run_this', 'manual__2022-10-13T21:33:13.093239+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/***_titanic.py', '--cfg-path', '/tmp/tmpdnl65pee']
[2022-10-13T21:33:15.467+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask also_run_this
[2022-10-13T21:33:15.468+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/***_titanic.py
[2022-10-13T21:33:15.491+0000] {logging_mixin.py:117} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dag.py:3425 RemovedInAirflow3Warning: Param `schedule_interval` is deprecated and will be removed in a future release. Please use `schedule` instead.
[2022-10-13T21:33:15.828+0000] {task_command.py:384} INFO - Running <TaskInstance: trabalho2.also_run_this manual__2022-10-13T21:33:13.093239+00:00 [running]> on host b572315ae1c7
[2022-10-13T21:33:15.975+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Marcos Vieira
AIRFLOW_CTX_DAG_ID=trabalho2
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-10-13T21:33:13.093239+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-13T21:33:13.093239+00:00
[2022-10-13T21:33:15.976+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-10-13T21:33:15.977+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -L -o" + target_dir + target_file + " " + source_file']
[2022-10-13T21:33:16.005+0000] {subprocess.py:86} INFO - Output:
[2022-10-13T21:33:16.008+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
[2022-10-13T21:33:16.008+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 2: syntax error: unexpected end of file
[2022-10-13T21:33:16.008+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2022-10-13T21:33:16.032+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-13T21:33:16.036+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=trabalho2, task_id=also_run_this, execution_date=20221013T213313, start_date=20221013T213315, end_date=20221013T213316
[2022-10-13T21:33:16.065+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task also_run_this (Bash command failed. The command returned a non-zero exit code 2.; 284)
[2022-10-13T21:33:16.092+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-13T21:33:16.145+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
